# Configuración de tema para Streamlit
# Basado en los design tokens del diseño Figma

[theme]
# Colores principales
primaryColor = "#1B59F8"           # Azul principal del diseño
backgroundColor = "#F9F9F9"        # Fondo gris claro
secondaryBackgroundColor = "#FFFFFF" # Fondo de cards
textColor = "#000000"              # Texto principal

# Fuente
font = "sans serif"  # Streamlit usará la fuente del sistema, CSS aplicará Inter

[server]
# Puerto por defecto
port = 8501

# Habilitar CORS si es necesario
enableCORS = false

# Habilitar XsrfProtection
enableXsrfProtection = true

[browser]
# Recolección de datos de uso
gatherUsageStats = false

# Título de la pestaña del navegador
# serverAddress = "localhost"
# serverPort = 8501